name: cicd
on:
  push:
    branches:
      - main

jobs:
  build_dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - run: pnpm install

      - name: build arco playground
        run: pnpm build:arco-vue

      - name: Upload build dist artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./packages/playground/dist

  magic_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - id: generate
        run: echo "VERSION=yiwwhl/harbor-design:$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    outputs:
      VERSION: ${{ steps.generate.outputs.VERSION }}

  build_image:
    needs: [build_dist, magic_version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: needs.magic_version.outputs.VERSION

  server_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            cd ${{ secrets.DEV_TARGET }} \
            sed -i "s|image:.*|image: needs.magic_version.outputs.VERSION|g" ${{ secrets.DEV_TARGET_FILE }}.yml \
            docker-compose down \
            docker-compose up -d \
          "
